ajout service galerie fonctionnel
SERVICE GALERIE fonctionnel :
élément a ajouter :
-méthode service qui prend  une galerie et le id d'un utilisateur pour la partager avec un autre utilisateur
-la methode put ne marche pas erreur
System.InvalidOperationException: The instance of entity type 'Galerie' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked.
-le client side est vide